random_seed: 12345 

n_sim_steps: 4
timestep: 0.01

fov: 4.7
# fov: 3.14
num_beams: 1080
# num_beams: 20

vehicle_width: 0.31
vehicle_length: 0.58

use_random_starts: True
save_scan_history: False


mu: 1.0489 
C_Sf: 4.718 
C_Sr: 5.4562 
lf: 0.15875 
lr: 0.17145 
h: 0.074 
m: 3.74 
I: 0.04712 
s_min: -0.4189 
s_max: 0.4189 
sv_min: -3.2 
sv_max: 3.2 
v_switch: 7.319 
a_max: 9.51 
v_min: -5.0 
v_max: 20.0 
width: 0.31 
length: 0.58
